import React from 'react'
import GirlFashion from '../../images/GirlFashion.jpg'

function Home() {
    return (
        <div className='container mx-auto content-center text-slate-600'>
            <div className="grid grid-cols-1 justify-items-center">
                <div>
                    <h1 className='text-5xl p-10'>Katie DeVault Constultation</h1>
                </div>
                <hr />
                <div className='container mx-auto p-6 text-center'>
                    <h2 className='font-bold'>Consultation</h2>
                    <p>Seasoned insight into Retail Market trends.</p>
                    <img className='inline h-64 w-100' src={GirlFashion} alt="" />
                </div>
                <hr />
                <div className='container mx-auto p-6 text-center'>
                    <h2 className='font-bold'>Market Research</h2>
                    <p>In-depth reports generated by throrough Market research of Retail based on Pricing, Sales, and Trends.</p>
                    <img className='inline h-64 w-100' src={GirlFashion} alt="" />
                </div>
                <hr />
                <div className='container mx-auto p-6 text-center'>
                    <h2 className='font-bold'>Fashion Advice</h2>
                    <p>You go, girl (or boy). I know what looks good.</p>
                    <img className='inline h-64 w-100' src={GirlFashion} alt="" />
                </div>
            </div>
        </div>
    )
}

export default Home