import React from 'react'
import GirlFashion from '../../images/GirlFashion.jpg'
import MainPic from '../../images/MainPic.jpg'
import NavBar from '../NavBar'

function Home() {
    return (
        <div className='container mx-auto content-center text-slate-600 divide-y min-h-screen font-italiana'>
            <NavBar />
            <div className='text-center text-slate-700 text-2xl p-4'>
                <h1>Retail Market Research just for you.</h1>
            </div>
            <img className='mx-auto h-auto w-2/3 pb-3' src={MainPic} alt="" />
            <div className="grid grid-cols-1 text-center divide-x">
                <div className='p-6'>
                    <h2 className='font-bold'>Consultation</h2>
                    <p>Seasoned insight into Retail Market trends.</p>
                    <img className='mx-auto h-auto w-2/3' src={GirlFashion} alt="" />
                </div>
                <div className='p-6'>
                    <h2 className='font-bold'>Market Research</h2>
                    <p>In-depth reports generated by throrough Market research of Retail based on Pricing, Sales, and Trends.</p>
                    <img className='mx-auto h-auto w-2/3' src={GirlFashion} alt="" />
                </div>
                <div className='p-6'>
                    <h2 className='font-bold'>Fashion Advice</h2>
                    <p>You go, girl (or boy). I know what looks good.</p>
                    <img className='mx-auto h-auto w-2/3' src={GirlFashion} alt="" />
                </div>
            </div>
        </div>
    )
}

export default Home