import './App.css';

function App() {
  return (
    <div className='container mx-auto content-center text-slate-600'>
      <div className="grid grid-cols-1 justify-items-center">
        <div className='container mx-auto p-6 text-center'>
          <h2 className='font-bold'>Consultation</h2>
          <p>Seasoned insight into Retail Market trends.</p>
        </div>
        <div className='container mx-auto p-6 text-center'>
          <h2 className='font-bold'>Market Research</h2>
          <p>In-depth reports generated by throrough Market research of Retail based on Pricing, Sales, and Trends.</p>
        </div>
        <div className='container mx-auto p-6 text-center'>
          <h2 className='font-bold'>Fashion Advice</h2>
          <p>You go, girl (or boy). I know what looks good.</p>
        </div>
      </div>
    </div>
  );
}

export default App;
